
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojclhlietdwbnjxlmzso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qY2xobGlldGR3Ym5qeGxtenNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3MjEyMzUsImV4cCI6MjA1NjI5NzIzNX0.lDLB92GDBdZD8ku2o9K7BI5Fdi2AoIcL4c7CLfXFROA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Doküman dosyalarını almak için yardımcı fonksiyon
export const getPublicDocumentUrl = (path: string) => {
  return supabase.storage.from('documents').getPublicUrl(path).data.publicUrl;
};
